services:
  mariadb:
    image: docker.io/bitnami/mariadb:latest
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
  wordpress:
    build:
      dockerfile: dockerfile
      context: .
    depends_on:
      - mariadb
    environment:
      - WORDPRESS_SKIP_BOOTSTRAP=no
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - WORDPRESS_DATABASE_HOST=mariadb
      - WORDPRESS_DATABASE_PORT_NUMBER=3306
      - WORDPRESS_DATABASE_USER=bn_wordpress
      - WORDPRESS_DATABASE_NAME=bitnami_wordpress
      - WORDPRESS_AUTO_UPDATE_LEVEL=minor
      - WORDPRESS_FIRST_NAME=Asim
      - WORDPRESS_LAST_NAME=TW
      - WORDPRESS_EMAIL=asim@asimt.sa
      - WORDPRESS_BLOG_NAME=Asim Main Site
      # - WORDPRESS_SMTP_HOST=nil
      # - WORDPRESS_SMTP_PORT_NUMBER=nil
      # - WORDPRESS_SMTP_USER=nil
      # - WORDPRESS_ENABLE_MULTISITE=true
      # - WORDPRESS_MULTISITE_NETWORK_TYPE=subdomain
      # - WORDPRESS_MULTISITE_HOST=asimt.sa
      # - WORDPRESS_MULTISITE_ENABLE_NIP_IO_REDIRECTION=true
      # - WORDPRESS_MULTISITE_HOST=7f000001.nip.io
      # - WORDPRESS_MULTISITE_FILEUPLOAD_MAXK=100200

      # - WORDPRESS_EXTRA_WP_CONFIG_CONTENT=no
      # - WORDPRESS_EXTRA_CLI_ARGS
      # - WORDPRESS_EXTRA_INSTALL_ARGS
      # - WORDPRESS_PLUGINS
      # - WORDPRESS_TABLE_PREFIX
      # - WORDPRESS_ENABLE_HTTPS
      # - WORDPRESS_BLOG_NAME
      # - WORDPRESS_SCHEME
      # - WORDPRESS_DATA_TO_PERSIST
    ports:
      - '80:8080'
      - '443:8443'
    volumes:
      - './src/main-theme:/main-theme'

volumes:
  mariadb_data:
    driver: local
